### ISSUE TITLE
Adding new label to label tree in annotation view/Largo

### ISSUE THREAD

**Issue by dlangenk** [biigle/core#667] opened 2023-09-28 11:04 UTC
Use case: You use Biigle in a two step approach. One person/machine detects all objects of interest without labeling them. An expert now wants to relabel the annotations to specific classes. The expert selects all/some of the objects of interest and notices while doing this that a specific label for labeling an object does not exist in the label tree. You can now switch to the label tree and add it, but reloading might mess with your current progress in Largo. Having a small plus symbol to add a label on the fly in the label tree would help a lot. More or less the same applies to annotating in Annotation view.

Like this for example:

![addLabel](https://github.com/biigle/core/assets/4822085/64a1fc0c-3a21-4f6c-a988-37054cc4b375)

**Comment by mzur** [comment] 2023-09-28 15:21
Duplicate of #585

**Closed by mzur** 2023-09-28 15:21 UTC

**Comment by dlangenk** [comment] 2023-09-29 07:19
However, isn't implementing a rather complicated technical solution with sockets a bit overkill in contrast to adding a text input and color picker for adding a new label. I get that arbitrary operations might be more complicated. But just adding a label as this is probably the most important case. From a user perspective I think it is kind of unintuitive going to a different page to affect the current view you are working on. Deleting labels, renaming labels etc. can of course still be done in the label tree view as this is not that important to do on the fly. Not sure about the create a new child label. But this would be okay for me to not have in the annotation/Largo view.

**Comment by mzur** [comment] 2023-10-02 08:24
Actually, implementing the idea of #585 with Websockets will be easier on a technical level than adding the "add label" function to the label trees tab. Also, it will provide the full feature set of adding/importing labels. I'm sure if we only implement adding labels at the root, there will be users asking why they cant create nested labels, or import them from WoRMS. Then we'll end up implementing the whole feature set of the label trees page but with a much more complicated UI.

I see how adding a label "right there" could be easier but right now, I prefer the solution in a separate window.

**Comment by dlangenk** [comment] 2023-10-02 08:41
What about adding a link behind an icon to the label tree at the top of each label tree section in Largo/Annotation View

**Comment by mzur** [comment] 2023-10-02 11:02
You mean here?

![bitmap](https://github.com/biigle/core/assets/2457311/211145e8-0d9d-4687-96f6-d068a8a12318)

A link could be useful in combination with #585.

**Comment by dlangenk** [comment] 2023-10-02 11:04
Yes. Probably a pen or a plus there. Together with the websockets solution it would not be as convinient, but already a quite intuitive solution

**Comment by dlangenk** [comment] 2024-10-15 09:15
Jaime Davies also brought this issue back to my attention since she advertised this two step approach in her Biigle workshop. I'd still prefer the more simple approach, but the sockets solution is still much more convenient than reloading. In Largo reloading the page is not possible without loosing process, thus a solution is very much needed there. Currently they are creating a lot of dummy labels and then renaming them after. This however is kind of error-prone.
